# ~/.config/starship.toml

#format = """
#$all\
#$fill\
#$time\
#$line_break\
#$aws\
#$gcloud\
#$openstack\
#$azure\
#$line_break\
#$battery\
#$status\
#$shell\
#$character
#"""

# Increase command timout. Git on macOS takes quite a long time
command_timeout = 2000

# Increase directory scan timeout. Default 30ms is to short for cold caches
scan_timeout = 150

[username]
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
ssh_symbol = "🌐"
#ssh_symbol = "🛰️"
format = "@[$hostname$ssh_symbol]($style) "

[directory]
truncation_length = 10

[git_branch]
format = '[\(](gray)[$branch(:$remote_branch)]($style)'
#format = "[$symbol$branch(:$remote_branch)]($style)"

[git_commit]
format = "[\\($hash$tag\\)]($style)"

[git_state]
style = "gray"
format = "[|$state( $progress_current/$progress_total)]($style)"

[git_status]
format = '([|$ahead_behind($all_status)]($style))[\)]($style) '
#format = '([\($ahead_behind(|$all_status)\)]($style) )'
conflicted = "[›‹${count}](bold red)"
ahead = "↑${count}"
behind = "↓${count}"
diverged = "↑${ahead_count}↓${behind_count}"
up_to_date = "[✓](green)"
untracked = "…"
stashed = '[\$$count](bold yellow)'
modified = "[*$count](blue)"
staged = "[+$count](yellow)"
renamed = "[»$count](cyan)"
deleted = "[-$count](red)"
style = "gray"

[java]
symbol = " "

[python]
symbol = " "

[terraform]
format = "[$symbol$workspace]($style) "
#format = "[$symbol]($style) "

[memory_usage]
threshold = -1
format = "$symbol [${ram}( | ${swap})]($style) "
#symbol = " "
symbol = "𓇲 "
disabled = true

# I don't use cloud accounts all that often, and they take up a LOT of space in
# the prompt. I need to figure out a way to temporarily enable them when in
# use. Maybe create some alias to the cloud CLI tools that use sed to change
# disabled to false, but not sure how and when to revert the change.
[aws]
symbol = " "
disabled = true

[gcloud]
format = '[$symbol$account(@$domain)(:$project)(\($region\))]($style) '
symbol = " "
disabled = true

[sudo]
symbol = "💀 "
disabled = false

[cmd_duration]
min_time = 0
#format = "⏱️ [$duration]($style) "
format = "🕑 [$duration]($style) "

[[battery.display]]
threshold = 20

[[battery.display]]
threshold = 33
style = "bold yellow"

[[battery.display]]
threshold = 97
style = "bold green"

[time]
style = "bold bright-black"
disabled = false

[status]
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[shell]
#fish_indicator = ""
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[fill]
symbol = " "
